@IsTest
private class Test_SalesOrderServiceRecordFlow {

    @TestSetup
    private static void setupTestData() {
        // mock data
    }

    @isTest
    private static void testUpdateItemsInOrder_forPriceOverride_DiscountIsApplied_Positive() {
        // test code
    }

    @isTest
    private static void testUpdateItemsInOrder_forPriceOverride_DiscountIsApplied_Negative() {
        // test code
    }

}